name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Build Application
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Push Image To Registry
      run: |
        docker push ${{ secrets.DOCKER_IMAGE }}
 

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
           docker pull ${{ secrets.DOCKER_IMAGE }}
           docker compose down ${{ secrets.SERVICE }}
           docker compose up -d
